name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup
      run: |
          cd GameSystem
          bash setup.sh
      
    - name: Build-GS
      run: |
          cd GameSystem
          bash build.sh

  build-windows:
    runs-on: windows-latest

    - name: Build-MC
      uses: jurpel/install-qt-action@v2
      with:
        version: '5.15.1'
        arch: 'win64_mingw81'

      run: |
          cd MapCreator
          cmake -DCMAKE_PREFIX_PATH=${{ github.workspace}}/Qt/5.15.1/win64_mingw81 -S . -B out
          cd out
          make
